development:
  adapter: postgresql
  encoding: unicode
  database: useframes_development
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: useframes_production
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: useframes_test
  pool: 5
